FROM debian

RUN apt-get update && apt-get upgrade -y && apt-get install -y build-essential git && \
	git clone https://github.com/off99555/Hello-C-and-Makefile.git hello
#https://github.com/off99555/Hello-C-and-Makefile.git
