FROM ruby
MAINTAINER sko <sko@student.42.us.org>
RUN apt-get update && \
	apt-get install -y build-essential libpq-dev nodejs sqlite3
# Resources:
# https://github.com/railstutorial/sample_app_2nd_ed
